### ISSUE TITLE
Built zip file is huge compared to building it manually

### ISSUE THREAD

**Issue by RafaelWO** [nhartland/love-build#10]
Hey, I noticed that the resulting zip files are pretty huge, especially the ones for windows (e.g. see [my release](https://github.com/RafaelWO/space-love/releases/tag/v0.4)).

When I do it manually (see [love2d wiki](https://love2d.org/wiki/Game_Distribution)), my win64 zip is **87.6MB**, but the artifact from the GitHub action is **659MB**.

Any idea why this is the case?

P.S. I also noticed that the file size seems to increase - in fact, double - per built application:

![image](https://user-images.githubusercontent.com/38643099/136148797-c6c1236a-2e71-49fd-b476-7509f981e7c4.png)

>80 * 2 ~= 166
166 * 2 ~= 329
329 * 2 ~= 659

**Comment by RafaelWO** [comment]
I dug a bit deeper and extracted the contents of the `.exe` (688MB big) within the `*win64.zip` and noticed that it contains a folder `release` (default output dir of the action) which contains the previously built files:

![image](https://user-images.githubusercontent.com/38643099/136955018-d7d81bff-4b65-4c34-9ffe-20af50558bdc.png)

I.e. I found the cause of this issue, now one has to solve it (I'm already on it, but I don't have much spare time for this). I probably will drop a PR in ~1-2 weeks.

**Comment by nhartland** [comment]
Hey, apologies for the delayed replies, for some reason I wasn't watching this repo (fixed that!).
Thanks for digging into this, and for the PR!
