### ISSUE TITLE
Error for building MacOS (löve 0.10.2)

### ISSUE THREAD

**Issue by RafaelWO** [nhartland/love-build#8]
Hi, first I would like to thank you for your work! I did not think that there exists an action for building love2d apps.

I'm getting an error for building my game with version love 0.10.2:

```
[...]
--2021-06-23 15:50:09--  https://github.com/love2d/love/releases/download/0.10.2/love-0.10.2-macos.zip
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-23 15:50:10 ERROR 404: Not Found.
```

I seems that this URL does not exist for this version of Löve. 

Is there a way of doing just the Windows build? Thanks!

**Comment by RafaelWO** [comment]
I opened a PR which should fix this error. Any idea how to test it?

**Comment by nhartland** [comment]
Thanks for working on this, I'll add some automated checks so that PRs should be verified automatically in the future.
